name: no_screenshot
description: Flutter plugin to enable, disable, toggle or stream screenshot activities in your application.
version: 0.3.4
homepage: https://flutterplaza.com
repository: https://github.com/FlutterPlaza/no_screenshot/releases/tag/v0.3.4

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterplaza.no_screenshot
        pluginClass: NoScreenshotPlugin
      ios:
        pluginClass: NoScreenshotPlugin
      macos:
        pluginClass: MacOSNoScreenshotPlugin
