name: no_screenshot
description: Flutter plugin to prevent screenshots, detect screen recording, and show blur/color/image overlays in the app switcher on Android, iOS, macOS, Linux, Windows, and Web.
version: 0.9.0
homepage: https://flutterplaza.com
repository: https://github.com/FlutterPlaza/no_screenshot

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterplaza.no_screenshot
        pluginClass: NoScreenshotPlugin
      ios:
        pluginClass: NoScreenshotPlugin
      macos:
        pluginClass: MacOSNoScreenshotPlugin
      linux:
        pluginClass: NoScreenshotPlugin
      windows:
        pluginClass: NoScreenshotPluginCApi
      web:
        pluginClass: NoScreenshotWeb
        fileName: no_screenshot_web.dart
