name: no_screenshot
description: Flutter plugin to prevent screenshots, detect screen recording, and show blur/color/image overlays in the app switcher on Android, iOS, macOS, and Linux.
version: 0.7.0
homepage: https://flutterplaza.com
repository: https://github.com/FlutterPlaza/no_screenshot/releases/tag/v0.7.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"
  flutter_driver:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterplaza.no_screenshot
        pluginClass: NoScreenshotPlugin
      ios:
        pluginClass: NoScreenshotPlugin
      macos:
        pluginClass: MacOSNoScreenshotPlugin
      linux:
        pluginClass: NoScreenshotPlugin
